# Generated by Django 2.1.2 on 2018-10-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetups', models.PositiveIntegerField(verbose_name='Meetups Conducted')),
                ('training_session', models.PositiveIntegerField(verbose_name='Training Sessions Conducted')),
                ('members', models.PositiveIntegerField(verbose_name='Total Members')),
                ('developers', models.PositiveIntegerField(verbose_name='Total Developers')),
            ],
        ),
    ]
