# Generated by Django 2.1.2 on 2018-10-17 14:27

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('main_file', models.FileField(upload_to=blog.models.get_blog_upload_path, validators=[blog.models.validate_blog_file_extension], verbose_name='Blog Content File')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_time', models.DateTimeField()),
                ('upvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_blog', to='blog.Vote'),
        ),
        migrations.AddField(
            model_name='blog',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_blog', to='blog.Vote'),
        ),
    ]
