# Generated by Django 2.0.6 on 2018-10-18 09:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181018_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_blog_image_upload_path),
        ),
    ]
