# Generated by Django 2.0.6 on 2018-10-18 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 16, 55, 58, 339905, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
