# Generated by Django 2.0.6 on 2018-10-18 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181018_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 16, 57, 22, 843166, tzinfo=utc), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
