# Generated by Django 2.1.2 on 2018-10-18 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181018_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 19, 14, 19, 635481, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
