# Generated by Django 2.1.2 on 2018-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181018_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='downvotes',
            field=models.ManyToManyField(null=True, related_name='downvoted_blog', to='blog.Vote'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='upvotes',
            field=models.ManyToManyField(null=True, related_name='upvoted_blog', to='blog.Vote'),
        ),
    ]
