# Generated by Django 2.1.2 on 2018-10-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181018_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='upvote_time',
            new_name='vote_time',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='upvoter',
            new_name='voter',
        ),
    ]
