# Generated by Django 2.1.2 on 2018-10-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181018_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='vote',
            name='upvote_downvote',
            field=models.SmallIntegerField(default=0, help_text='-1 for downvote, 0 for none, 1 for upvote'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='blog',
            name='downvotes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Downvotes'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='blog',
            name='upvotes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Upvotes'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
