# Generated by Django 2.1.2 on 2018-10-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181018_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
