# Generated by Django 2.1.2 on 2018-10-18 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181018_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='upvote_downvote',
            field=models.SmallIntegerField(default=0, help_text='-1 for downvote, 0 for none, 1 for upvote', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
