# Generated by Django 2.1.2 on 2018-10-19 08:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181019_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=15, validators=[blog.models.tag_name_validator], verbose_name='Tag Name'),
        ),
    ]
