# Generated by Django 2.1.2 on 2018-10-19 17:18

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_auto_20181019_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, validators=[blog.models.blog_title_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('slug', 'author')},
        ),
    ]
