# Generated by Django 2.1.2 on 2018-10-19 19:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20181019_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='disqus_identifier',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(upload_to=blog.models.get_blog_image_upload_path),
        ),
    ]
