# Generated by Django 2.1.2 on 2018-10-20 13:48

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_auto_20181019_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='This is the title of your blog. (limit to 50 characters)', max_length=50, validators=[blog.models.blog_title_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('slug', 'author')},
        ),
    ]
