# Generated by Django 2.1.2 on 2018-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20181020_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='This slug will form the url of your blog. The Url will be blogs/blog/<your username>/<slug> (Limit to 60 characters)', max_length=60, null=True),
        ),
    ]
