# Generated by Django 2.1.2 on 2018-10-20 14:25

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20181020_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='This is the main content of the blog. You can style the content , put images, videos, code-snippets and a lot more things directly into the editor', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(help_text='This picture is the cover image of your blog.', upload_to=blog.models.get_blog_image_upload_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, help_text='This is the short description that appears in blog list. (Limit to 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='This slug will form the url of your blog. The Url will be blogs/blog/<your username>/<slug>', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Please select relevant tags for your blog. or create a new tag', to='blog.Tag'),
        ),
    ]
