# Generated by Django 2.1.2 on 2018-10-19 06:56

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20181018_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='/static/registration/default_profile_pic.jpg', upload_to=registration.models.get_user_profile_pic_upload_path),
        ),
    ]
