# Generated by Django 2.1.2 on 2018-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181019_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blog_create_permission',
            field=models.BooleanField(default=False),
        ),
    ]
